name: Sync upstream changes

on:
  schedule:
    - cron: '0 3 * * *'  # Daily at 03:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout forked repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0  # Full history for merging

      - name: Set up Git
        run: |
          git config --global user.email "bot@lowcoder.org"
          git config --global user.name "Lowcoder Sync Bot"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/lowcoder-org/lowcoder.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main -Xours --allow-unrelated-histories || true

      - name: Remove protected files from satellite repo
        run: |
          echo "Deleting protected files from satellite clone"
          rm -f .gitbook.yaml
          rm -f .sonar-project.properties
          rm -f .codeql/codeql-config.yaml
          rm -f .gitbook/dependabot.yml
          rm -f .gitbook/workflows/client.yml
          rm -f .gitbook/workflows/codeql.yml
          rm -f .gitbook/workflows/docker-images.yml
          rm -f .gitbook/workflows/node-service.yml
          rm -f .gitbook/workflows/publish-lowcoder-cli.yml
          rm -f .gitbook/workflows/publish-lowcoder-comps.yml
          rm -f .gitbook/workflows/publish-lowcoder-core.yml
          rm -f .gitbook/workflows/publish-lowcoder-sdk.yml
          rm -f .gitbook/workflows/sonarcloud.yml
          echo "Protected files removed."

      - name: Commit and push if changes
        run: |
          git status
          if [[ -n "$(git status --porcelain)" ]]; then
            git commit -am "Sync from upstream (preserved protected files)"
            git push origin main
          else
            echo "No changes to commit."
          fi
